# Generated by Django 2.0.3 on 2018-03-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('street', models.IntegerField(max_length=10)),
                ('house_number', models.IntegerField(max_length=10)),
                ('app_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Work')])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=62)),
                ('description', models.TextField(max_length=200)),
                ('mail', models.ForeignKey(on_delete=None, to='contact_book.Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20)),
                ('type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Work')])),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(on_delete=None, to='contact_book.Phone'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='persons',
            field=models.ManyToManyField(to='contact_book.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='occupant',
            field=models.ForeignKey(on_delete=None, to='contact_book.Person'),
        ),
    ]
