# Generated by Django 2.0.3 on 2018-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_auto_20180327_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='mail',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=None, to='contact_book.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=None, to='contact_book.Person'),
            preserve_default=False,
        ),
    ]
