# Generated by Django 2.0.3 on 2018-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0003_auto_20180327_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='occupant',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=None, to='contact_book.Address'),
        ),
    ]
